export const metadata = {
  title: 'Terms of Service — Briefly',
  description: 'The rules for using Briefly.',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 px-8 py-5">
        <a href="/" className="text-lg font-bold text-gray-900 hover:opacity-80 transition-opacity">
          📬 Briefly
        </a>
      </nav>

      <article className="max-w-2xl mx-auto px-6 py-12 prose prose-sm prose-gray">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: June 22, 2026</p>

        <p>
          These terms govern your use of Briefly. By signing in you agree to them. If you do not agree, do not use the service.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">What Briefly does</h2>
        <p>
          Briefly reads emails from senders you choose, sends the content to an AI model, and delivers a recap to your inbox on a schedule you set. The service is provided as-is.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Your account</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>You must be at least 13 years old to use Briefly.</li>
          <li>You are responsible for the Google account you sign in with.</li>
          <li>Don&apos;t share your account with others.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-10 mb-3">What you can&apos;t do</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use Briefly to read someone else&apos;s email without their permission.</li>
          <li>Use Briefly to harvest, resell, or redistribute mail content.</li>
          <li>Attempt to bypass our rate limits or extract data beyond your own account.</li>
          <li>Reverse engineer, decompile, or attempt to access source code through unauthorized means.</li>
          <li>Use Briefly for anything illegal or to harm others.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-10 mb-3">AI output</h2>
        <p>
          Digests are generated by a large language model. Output can be wrong, miss things, or hallucinate. Treat the digest as a summary, not a substitute for reading important messages. Briefly is not liable for missed deadlines, missed opportunities, or any decisions you make based on the digest.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Pricing and billing</h2>
        <p>
          Briefly has a free tier (one stream, weekly delivery) and a Pro tier ($7/month, billed monthly). Pro starts with a 14-day free trial. You can cancel anytime from the dashboard. Cancellation takes effect at the end of the current billing period. We do not issue refunds for partial months. If we raise prices we will notify you at least 30 days before the change.
        </p>
        <p className="mt-3">
          Subscriptions are processed by Stripe. By starting a trial you agree to Stripe&apos;s terms in addition to these.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Service availability</h2>
        <p>
          We aim for high uptime but make no guarantees. Scheduled digests may be delayed or skipped during outages of any of our providers (Google, Anthropic, Resend, Supabase, Vercel).
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Termination</h2>
        <p>
          You can delete your account anytime from the dashboard. We can suspend or terminate accounts that violate these terms, abuse the service, or threaten its safety. We will tell you why if we do this.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Limitation of liability</h2>
        <p>
          To the extent allowed by law, Briefly is not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability for any claim is capped at the amount you paid us in the 12 months before the claim, or $100 if you paid nothing.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Changes</h2>
        <p>
          We may update these terms. Material changes get emailed to you in advance. Continued use after the change date counts as acceptance.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Governing law</h2>
        <p>
          California law governs these terms. Disputes will be resolved in the state or federal courts of San Luis Obispo County, California.
        </p>

        <h2 className="text-xl font-semibold mt-10 mb-3">Contact</h2>
        <p>
          Questions: <a href="mailto:jasparbbernstein@gmail.com" className="text-blue-600 hover:underline">jasparbbernstein@gmail.com</a>
        </p>
      </article>
    </main>
  )
}
